.\"
.\" (C) Copyright 2022 Alec Leamas <leamas.alec@gmail.com>,
.\"
.TH Opencpn-cmd 1 "Dec 2022"

.SH NAME
opencpn-cmd \- Chartplotter and GPS Navigation Software CLI interface
.SH SYNOPSIS
.B opencpn-cmd
.RI [ options ]
.SH DESCRIPTION
opencpn-cmd provides command line  access to some basic functionality
available in opencpn.
It is in a very preliminart alpha state.
.P
Currently, opencpn-cmd supports various functions to load plugins and display
some configuration information.

.SH OPTIONS
.TP
.B \-h, \-\-help
Show help info.

.SH SEE ALSO
.br
opencpn(1)
