/* Autogenerated by png2wx.pl on Thu Nov 25 13:25:00 2010 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_dashboard_pi;
extern wxBitmap *_img_dashboard;
extern wxBitmap *_img_dial;
extern wxBitmap *_img_instrument;
extern wxBitmap *_img_minus;
extern wxBitmap *_img_plus;

#endif /* ICONS_H */
