/* Autogenerated by png2wx.pl on Mon Sep  6 23:26:50 2010 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_dashboard;
extern wxBitmap *_img_dial;
extern wxBitmap *_img_instrument;

#endif /* ICONS_H */
