var dir_ee3a62bdded23c509e986da0559bff56 =
[
    [ "ais_bitstring.h", "ais__bitstring_8h_source.html", null ],
    [ "ais_decoder.h", "ais__decoder_8h_source.html", null ],
    [ "ais_defs.h", "ais__defs_8h_source.html", null ],
    [ "ais_state_vars.h", "ais__state__vars_8h.html", "ais__state__vars_8h" ],
    [ "ais_target_data.h", "ais__target__data_8h_source.html", null ],
    [ "atomic_queue.h", "atomic__queue_8h_source.html", null ],
    [ "base_platform.h", "base__platform_8h_source.html", null ],
    [ "catalog_handler.h", "catalog__handler_8h_source.html", null ],
    [ "catalog_parser.h", "catalog__parser_8h_source.html", null ],
    [ "certificates.h", "certificates_8h_source.html", null ],
    [ "chartdata_input_stream.h", "chartdata__input__stream_8h_source.html", null ],
    [ "cli_platform.h", "cli__platform_8h_source.html", null ],
    [ "cmdline.h", "cmdline_8h.html", "cmdline_8h" ],
    [ "comm_ais.h", "comm__ais_8h_source.html", null ],
    [ "comm_appmsg.h", "comm__appmsg_8h_source.html", null ],
    [ "comm_appmsg_bus.h", "comm__appmsg__bus_8h_source.html", null ],
    [ "comm_bridge.h", "comm__bridge_8h_source.html", null ],
    [ "comm_can_util.h", "comm__can__util_8h_source.html", null ],
    [ "comm_decoder.h", "comm__decoder_8h_source.html", null ],
    [ "comm_driver.h", "comm__driver_8h_source.html", null ],
    [ "comm_drv_factory.h", "comm__drv__factory_8h_source.html", null ],
    [ "comm_drv_file.h", "comm__drv__file_8h_source.html", null ],
    [ "comm_drv_n0183.h", "comm__drv__n0183_8h_source.html", null ],
    [ "comm_drv_n0183_android_bt.h", "comm__drv__n0183__android__bt_8h_source.html", null ],
    [ "comm_drv_n0183_android_int.h", "comm__drv__n0183__android__int_8h_source.html", null ],
    [ "comm_drv_n0183_net.h", "comm__drv__n0183__net_8h_source.html", null ],
    [ "comm_drv_n0183_serial.h", "comm__drv__n0183__serial_8h.html", "comm__drv__n0183__serial_8h" ],
    [ "comm_drv_n2k.h", "comm__drv__n2k_8h_source.html", null ],
    [ "comm_drv_n2k_net.h", "comm__drv__n2k__net_8h_source.html", null ],
    [ "comm_drv_n2k_serial.h", "comm__drv__n2k__serial_8h_source.html", null ],
    [ "comm_drv_n2k_socketcan.h", "comm__drv__n2k__socketcan_8h_source.html", null ],
    [ "comm_drv_registry.h", "comm__drv__registry_8h_source.html", null ],
    [ "comm_drv_signalk.h", "comm__drv__signalk_8h_source.html", null ],
    [ "comm_drv_signalk_net.h", "comm__drv__signalk__net_8h_source.html", null ],
    [ "comm_n0183_output.h", "comm__n0183__output_8h_source.html", null ],
    [ "comm_navmsg.h", "comm__navmsg_8h_source.html", null ],
    [ "comm_navmsg_bus.h", "comm__navmsg__bus_8h_source.html", null ],
    [ "comm_out_queue.h", "comm__out__queue_8h_source.html", null ],
    [ "comm_util.h", "comm__util_8h_source.html", null ],
    [ "comm_vars.h", "comm__vars_8h_source.html", null ],
    [ "config_vars.h", "config__vars_8h_source.html", null ],
    [ "conn_params.h", "conn__params_8h_source.html", null ],
    [ "cutil.h", "cutil_8h_source.html", null ],
    [ "dbus_client.h", "dbus__client_8h_source.html", null ],
    [ "dbus_instance_check.h", "dbus__instance__check_8h_source.html", null ],
    [ "dbus_server.h", "dbus__server_8h.html", "dbus__server_8h" ],
    [ "downloader.h", "downloader_8h_source.html", null ],
    [ "ds_porttype.h", "ds__porttype_8h_source.html", null ],
    [ "garmin_protocol_mgr.h", "garmin__protocol__mgr_8h_source.html", null ],
    [ "garmin_wrapper.h", "garmin__wrapper_8h_source.html", null ],
    [ "geodesic.h", "geodesic_8h_source.html", null ],
    [ "georef.h", "georef_8h_source.html", null ],
    [ "gui.h", "gui_8h.html", "gui_8h" ],
    [ "hyperlink.h", "hyperlink_8h_source.html", null ],
    [ "idents.h", "idents_8h_source.html", null ],
    [ "instance_check.h", "instance__check_8h_source.html", null ],
    [ "ipc_api.h", "ipc__api_8h_source.html", null ],
    [ "json_event.h", "json__event_8h_source.html", null ],
    [ "linux_devices.h", "linux__devices_8h.html", "linux__devices_8h" ],
    [ "linux_usb_watch.h", "linux__usb__watch_8h.html", [
      [ "LinuxUsbWatchDaemon", "classLinuxUsbWatchDaemon.html", "classLinuxUsbWatchDaemon" ]
    ] ],
    [ "local_api.h", "local__api_8h.html", "local__api_8h" ],
    [ "logger.h", "logger_8h_source.html", null ],
    [ "macutils.h", "macutils_8h_source.html", null ],
    [ "MarkIcon.h", "MarkIcon_8h_source.html", null ],
    [ "mdns_cache.h", "mdns__cache_8h_source.html", null ],
    [ "mDNS_query.h", "mDNS__query_8h_source.html", null ],
    [ "mDNS_service.h", "mDNS__service_8h_source.html", null ],
    [ "meteo_points.h", "meteo__points_8h_source.html", null ],
    [ "multiplexer.h", "multiplexer_8h_source.html", null ],
    [ "nav_object_database.h", "nav__object__database_8h_source.html", null ],
    [ "navutil_base.h", "navutil__base_8h_source.html", null ],
    [ "nmea_ctx_factory.h", "nmea__ctx__factory_8h_source.html", null ],
    [ "nmea_log.h", "nmea__log_8h_source.html", null ],
    [ "ocpn_types.h", "ocpn__types_8h_source.html", null ],
    [ "ocpn_utils.h", "ocpn__utils_8h_source.html", null ],
    [ "own_ship.h", "own__ship_8h_source.html", null ],
    [ "peer_client.h", "peer__client_8h_source.html", null ],
    [ "pincode.h", "pincode_8h_source.html", null ],
    [ "plugin_blacklist.h", "plugin__blacklist_8h_source.html", null ],
    [ "plugin_cache.h", "plugin__cache_8h_source.html", null ],
    [ "plugin_handler.h", "plugin__handler_8h_source.html", null ],
    [ "plugin_loader.h", "plugin__loader_8h_source.html", null ],
    [ "plugin_paths.h", "plugin__paths_8h_source.html", null ],
    [ "position_parser.h", "position__parser_8h_source.html", null ],
    [ "rest_server.h", "rest__server_8h_source.html", null ],
    [ "route.h", "route_8h_source.html", null ],
    [ "route_point.h", "route__point_8h_source.html", null ],
    [ "routeman.h", "routeman_8h_source.html", null ],
    [ "safe_mode.h", "safe__mode_8h_source.html", null ],
    [ "select.h", "select_8h_source.html", null ],
    [ "select_item.h", "select__item_8h_source.html", null ],
    [ "semantic_vers.h", "semantic__vers_8h_source.html", null ],
    [ "SencManager.h", "model_2include_2model_2SencManager_8h_source.html", null ],
    [ "ser_ports.h", "ser__ports_8h_source.html", null ],
    [ "std_instance_chk.h", "std__instance__chk_8h_source.html", null ],
    [ "sys_events.h", "sys__events_8h_source.html", null ],
    [ "track.h", "track_8h_source.html", null ],
    [ "usb_watch_daemon.h", "usb__watch__daemon_8h.html", [
      [ "UsbWatchDaemon", "classUsbWatchDaemon.html", "classUsbWatchDaemon" ],
      [ "DummyWatchDaemon", "classDummyWatchDaemon.html", "classDummyWatchDaemon" ]
    ] ],
    [ "wait_continue.h", "wait__continue_8h.html", [
      [ "WaitContinue", "classWaitContinue.html", "classWaitContinue" ]
    ] ],
    [ "win_usb_watch.h", "win__usb__watch_8h.html", [
      [ "WinUsbWatchDaemon", "classWinUsbWatchDaemon.html", "classWinUsbWatchDaemon" ]
    ] ],
    [ "wx28compat.h", "wx28compat_8h_source.html", null ],
    [ "wx_instance_chk.h", "wx__instance__chk_8h_source.html", null ]
];