//////////////////////////////////////////////////////////////////////////////
// Name:        SVGDefinitionSrcElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_DEFINITION_SRC_ELEMENT_H
#define WX_SVG_DEFINITION_SRC_ELEMENT_H

#include "SVGElement.h"
#include "String_wxsvg.h"
#include "Element.h"

class wxSVGDefinitionSrcElement:
  public wxSVGElement
{
  public:
    wxSVGDefinitionSrcElement(wxString tagName = wxT("definition-src")):
      wxSVGElement(tagName) {}
    virtual ~wxSVGDefinitionSrcElement() {}
    wxSvgXmlNode* CloneNode(bool deep = true) { return new wxSVGDefinitionSrcElement(*this); }
    bool HasAttribute(const wxString& name) const;
    wxString GetAttribute(const wxString& name) const;
    bool SetAttribute(const wxString& name, const wxString& value);
    wxSvgXmlAttrHash GetAttributes() const;
    virtual wxSVGDTD GetDtd() const { return wxSVG_DEFINITION_SRC_ELEMENT; }
};

#endif // WX_SVG_DEFINITION_SRC_ELEMENT_H
