//////////////////////////////////////////////////////////////////////////////
// Name:        SVGHKernElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_H_KERN_ELEMENT_H
#define WX_SVG_H_KERN_ELEMENT_H

#include "SVGElement.h"
#include "String_wxsvg.h"
#include "Element.h"

class wxSVGHKernElement:
  public wxSVGElement
{
  public:
    wxSVGHKernElement(wxString tagName = wxT("hkern")):
      wxSVGElement(tagName) {}
    virtual ~wxSVGHKernElement() {}
    wxSvgXmlNode* CloneNode(bool deep = true) { return new wxSVGHKernElement(*this); }
    bool HasAttribute(const wxString& name) const;
    wxString GetAttribute(const wxString& name) const;
    bool SetAttribute(const wxString& name, const wxString& value);
    wxSvgXmlAttrHash GetAttributes() const;
    virtual wxSVGDTD GetDtd() const { return wxSVG_HKERN_ELEMENT; }
};

#endif // WX_SVG_H_KERN_ELEMENT_H
