//////////////////////////////////////////////////////////////////////////////
// Name:        SVGTRefElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_T_REF_ELEMENT_H
#define WX_SVG_T_REF_ELEMENT_H

#include "SVGTextPositioningElement.h"
#include "SVGURIReference.h"
#include "String_wxsvg.h"
#include "Element.h"
#include "SVGAnimatedType.h"

class wxSVGTRefElement:
  public wxSVGTextPositioningElement,
  public wxSVGURIReference
{
  public:
    wxSVGTRefElement(wxString tagName = wxT("tref")):
      wxSVGTextPositioningElement(tagName) {}
    virtual ~wxSVGTRefElement() {}
    wxSvgXmlNode* CloneNode(bool deep = true) { return new wxSVGTRefElement(*this); }
    bool HasAttribute(const wxString& name) const;
    wxString GetAttribute(const wxString& name) const;
    bool SetAttribute(const wxString& name, const wxString& value);
    wxSvgXmlAttrHash GetAttributes() const;
    bool SetAnimatedValue(const wxString& name, const wxSVGAnimatedType& value);
    virtual wxSVGDTD GetDtd() const { return wxSVG_TREF_ELEMENT; }
};

#endif // WX_SVG_T_REF_ELEMENT_H
