# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "ON")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "OFF")
SET(CPACK_BINARY_ZIP "OFF")
SET(CPACK_BUILDWIN_DIR "P:/working area/opencpn/remote/jongough/OpenCPN/buildwin")
SET(CPACK_CMAKE_GENERATOR "Visual Studio 10")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "NSIS")
SET(CPACK_INSTALL_CMAKE_PROJECTS "P:/working area/opencpn/remote/jongough/OpenCPN/build-win;opencpn;ALL;/")
SET(CPACK_INSTALL_PREFIX "C:/Program Files/OpenCPN")
SET(CPACK_MODULE_PATH "P:/working area/opencpn/remote/jongough/OpenCPN/")
SET(CPACK_NSIS_DIR "P:/working area/opencpn/remote/jongough/OpenCPN/buildwin/NSIS_Unicode")
SET(CPACK_NSIS_DISPLAY_NAME "OpenCPN 3.3.2303")
SET(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
SET(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "ExecWait '\"$INSTDIR\\vc10\\vcredist_x86.exe\" /q /norestart' $0\n; Remove folder\n  RMDir /r \"$INSTDIR\\vc10\"\n\n")
SET(CPACK_NSIS_INSTALLED_ICON_NAME "opencpn.exe")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "OpenCPN 3.3.2303")
SET(CPACK_NSIS_PACKAGE_NAME_LC "opencpn")
SET(CPACK_OUTPUT_CONFIG_FILE "P:/working area/opencpn/remote/jongough/OpenCPN/build-win/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "P:/working area/opencpn/remote/jongough/OpenCPN/README")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OpenCPN 3.3.2303")
SET(CPACK_PACKAGE_EXECUTABLES "opencpn;OpenCPN")
SET(CPACK_PACKAGE_FILE_NAME "opencpn_3.3.2303_setup")
SET(CPACK_PACKAGE_ICON "P:/working area/opencpn/remote/jongough/OpenCPN/src/bitmaps\\opencpn.ico")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "OpenCPN 3.3.2303")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "OpenCPN 3.3.2303")
SET(CPACK_PACKAGE_NAME "OpenCPN")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "opencpn.org")
SET(CPACK_PACKAGE_VERSION "3.3.2303")
SET(CPACK_PACKAGE_VERSION_MAJOR "3")
SET(CPACK_PACKAGE_VERSION_MINOR "3")
SET(CPACK_PACKAGE_VERSION_PATCH "2303")
SET(CPACK_RESOURCE_FILE_LICENSE "P:/working area/opencpn/remote/jongough/OpenCPN/data/license.txt")
SET(CPACK_RESOURCE_FILE_README "P:/working area/opencpn/remote/jongough/OpenCPN/README")
SET(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files/CMake 2.8/share/cmake-2.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_SOURCE_IGNORE_FILES "\\.cvsignore$;^P:/working area/opencpn/remote/jongough/OpenCPN.*/CVS/;^P:/working area/opencpn/remote/jongough/OpenCPN/build*;^/*")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "P:/working area/opencpn/remote/jongough/OpenCPN/build-win/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_SYSTEM_NAME "win32")
SET(CPACK_TOPLEVEL_TAG "win32")
SET(CPACK_WIX_SIZEOF_VOID_P "4")
