/* Autogenerated by png2wx.pl on Mon Apr  4 00:05:00 2011 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_logbook_pi;

#endif /* ICONS_H */
