/* Autogenerated by png2wx.pl on Wed Apr 25 13:44:42 2012 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_wmm;
extern wxBitmap *_img_wmm_pi;
extern wxBitmap *_img_wmm_live;

#endif /* ICONS_H */
