#!/usr/bin/python3

"""
Given some XML metadata input files build a combined output file
which could be used as the ocpn-plugins.xml plugin catalogue.

Usage:
    metadata-builder [xml input files...]  > ocpn-plugins.xml

"""

import xml.etree.ElementTree as ET
import xml.dom.minidom as minidom
import sys

def main():
    """Indeed: main program."""

    tree = ET.Element('plugins')
    for path in sys.argv[1:]:
        subtree = ET.parse(path)
        subtree.getroot().tag = 'plugin'
        tree.append(subtree.getroot())
    dom = minidom.parseString(ET.tostring(tree))
    for line in dom.toprettyxml(indent="  ").split("\n"):
        line = line.rstrip()
        if line:
            print(line)

if __name__ == '__main__':
    main()
