

# license.html and license.txt is referenced in the code.
usr/share/locale/*/LC_MESSAGES/*.mo
usr/share/opencpn/license.html
usr/share/opencpn/license.txt
usr/share/opencpn/ocpn-plugins.xml
usr/share/opencpn/opencpn.png
usr/share/opencpn/gshhs
usr/share/opencpn/plugins/chartdldr_pi/data/doc/advanced.html usr/share/doc/opencpn-data/chartdldr_pi
usr/share/opencpn/plugins/chartdldr_pi/data/doc/basic.html usr/share/doc/opencpn-data/chartdldr_pi
usr/share/opencpn/plugins/chartdldr_pi/data/doc/index.html usr/share/doc/opencpn-data/chartdldr_pi
usr/share/opencpn/plugins
usr/share/opencpn/s57data
usr/share/opencpn/sounds/*bells.wav
usr/share/opencpn/tcdata/HARMONIC.IDX
usr/share/opencpn/tcdata/HARMONIC
usr/share/opencpn/uidata
usr/share/opencpn/doc/help_web.html
usr/share/opencpn/LINUX_DEVICES.md usr/share/doc/opencpn-data
usr/share/opencpn/sounds/README.bells usr/share/doc/opencpn-data
usr/share/opencpn/tcdata/README.harmonics usr/share/doc/opencpn-data
