.TH OPENCPN 1
.SH NAME
OpenCPN \- a concise ChartPlotter/Navigator
.SH SYNOPSIS
.B opencpn [-h] [--verbose]
.SH DESCRIPTION
OpenCPN is a free software (GPL) project to create a concise chart plotter and navigation software for use as an underway or planning tool.

Current features:
.IP \[bu] 2
GPS/GPSD Postition Input
.IP \[bu]
BSB Raster Chart Display
.IP \[bu]
S57 Vector ENC Chart Display
.IP \[bu]
C\-MAP Vector Chart Display (CM93/2)
.IP \[bu]
AIS Input Decoding
.IP \[bu]
Waypoint / Autopilot Navigation
.IP \[bu]
International Language Support
.IP \[bu]
Cross-platform support
.IP \[bu]
Grib Weather Overlay
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help
.TP
.B \-\-verbose
Generate verbose log messages
.SH "SEE ALSO"
None.
.SH AUTHORS
dsr <bdbcat@yahoo.com>.
