/* Autogenerated by png2wx.py on Fri Oct 27 20:45:35 2017 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_AA1ChartNavHelper;
extern wxBitmap *_img_AA1ChartNavHelper_pi;

#endif /* ICONS_H */
