add_definitions(-g -funwind-tables -ffast-math -D_GNU_SOURCE)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fpermissive")
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^arm")
    add_definitions(-fsingle-precision-constant)
    if(NOT BCMHOST)
        add_definitions(-mfpu=neon -march=armv7-a -mcpu=cortex-a8 -mtune=cortex-a8)
    endif()
endif()
