/* Autogenerated by png2wx.pl on Thu Nov  4 13:06:52 2010 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_grib_pi;
extern wxBitmap *_img_grib;

#endif /* ICONS_H */
