/* Autogenerated by png2wx.pl on Wed Apr  6 10:14:37 2011 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_chartdldr;
extern wxBitmap *_img_chartdldr_pi;

#endif /* ICONS_H */
