/* Autogenerated by png2wx.pl on Fri Jun 22 12:43:35 2012 */
/* Modified by hand for namespace support */

#ifndef ICONS_H
#define ICONS_H 1

#include "pi_common.h"

PLUGIN_BEGIN_NAMESPACE

extern void initialize_images(void);

extern wxBitmap *_img_radar_amber;
extern wxBitmap *_img_radar_amber_slave;
extern wxBitmap *_img_radar_blank;
extern wxBitmap *_img_radar_blank_slave;
extern wxBitmap *_img_radar_green;
extern wxBitmap *_img_radar_green_slave;
extern wxBitmap *_img_radar_red;
extern wxBitmap *_img_radar_red_slave;

PLUGIN_END_NAMESPACE

#endif /* ICONS_H */
