/* Autogenerated by png2wx.pl on Tue Jul  8 18:19:35 2014 */
#ifndef YACHT_LOST_H
#define YACHT_LOST_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_yacht_lost;

#endif /* YACHT_LOST_H */
