/* Autogenerated by png2wx.pl on Tue Jul  8 18:19:49 2014 */
#ifndef YACHT_ALARM_H
#define YACHT_ALARM_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_yacht_alarm;

#endif /* YACHT_ALARM_H */
